name: PHP CS for diff lines

on:
  pull_request:
    # branches:
    paths:
      - '**.php'

jobs:
  php-cs:
    name: PHP CS of changed files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: cs2pr, phpcs # cs2prいらんか？
      - name: Fetch
        run: git fetch origin ${{ github.base_ref }} --depth=1
      - name: Git diff
        id: git-diff-changed-files
        run: echo "changed_files=$(git diff --name-only origin/${{ github.base_ref }} HEAD -- '*.php')" >> $GITHUB_OUTPUT
      - name: Echo # 後々削除
        run: echo ${{ steps.git-diff-changed-files.outputs.changed_files }}
      - name: Run phpcs
        run: phpcs -q --report=checkstyle --standard=PSR12 ${{ steps.git-diff-changed-files.outputs.changed_files }}
